"""Section 4 of the randomized-implementation suite -- the implementation
ledger -- and the six .tex fragment writers behind the thesis tables.
write_fragments() is reached only from randomized_implementations.py's
__main__ guard; importing any module of the suite writes nothing.

randomized_implementations.py is the suite's entry point -- its docstring
carries the R1/R2 protocol definitions, the kappa/eta pin, the findings
index, the module map and the run instructions -- and each finding's full
account lives in the docstring of the module that proves it;
`cd code && uv run randomized_implementations.py` runs the whole suite.
Captions live here, not in the .tex.
"""

import math
import re

import numpy as np
import sympy as sp
from sympy import Matrix, sqrt

from povm_properties import EXPECTED_DESIGN   # the ladder's one source of truth

from randomized_core import (DATA, SOLIDS, COVARIANCE, load_vertices,
                             load_rotations, load_atlas, rot_key,
                             is_decomposable, design_strength, by_order,
                             two_bars, atlas_vertices, best_circuits,
                             coset_representatives, atlas_gates, bloch_matrix,
                             exact_rotations, det_witness, twirl_bar,
                             rank_one_twirl, REORIENT)
from randomized_decker import decker_vertices

# ---------------------------------------------------------------------------
# Section 4: the implementation ledger
# ---------------------------------------------------------------------------

def print_ledger():
    demand = {"tetrahedron": "sqrt3", "octahedron": "-- (none)", "cube": "sqrt3",
              "icosahedron": "sqrt(5+2 sqrt5)", "dodecahedron": "sqrt3"}
    draw = {"octahedron": "2T", "cube": "2T", "icosahedron": "2T",
            "dodecahedron": "2I"}
    per_shot = {"octahedron": "depth <= 2, 0 Phi, A = I",
                "cube": "depth <= 2, 0 Phi, + A",
                "icosahedron": "depth <= 2, 0 Phi, + A",
                "dodecahedron": "depth <= 4, <= 1 Phi (mean 0.8), + A"}
    ancillas = {"tetrahedron": 1, "octahedron": 2, "cube": 2,
                "icosahedron": 3, "dodecahedron": 4}
    print(f"  {'POVM (V)':18s} {'native anc.':>11s}  {'field demand':>15s}  {'proj. draw':>10s}  projective per-shot")
    print("  " + "-" * 92)
    for solid in SOLIDS:
        V = len(load_vertices(solid))
        anc = math.ceil(math.log2(V)) - 1    # Naimark register dim >= V
        assert anc == ancillas[solid]
        print(f"  {solid:12s} ({V:2d})  {anc:>10d}  {demand[solid]:>15s}"
              f"  {draw.get(solid, '--'):>10s}  {per_shot.get(solid, '-- (indecomposable)')}")
    print("  (native ancillas: a Naimark register of dim >= V needs ceil(log2 V) qubits")
    print("   incl. the system -- minimal within the dilation route, whose radicals are")
    print("   forced by finding 3. twirled-native = native + the same 2T draw on every")
    print("   row: 0 Phi, depth <= 2. estimator-channel factors: T_zz (randomized-")
    print("   projective) vs tr(T)/3 (twirled-native); native instead ASSUMES")
    print("   depolarizing and corrects a calibrated scalar, with the known blind spot.)")


# ---------------------------------------------------------------------------
# Fragment emission: the ledger, its Appendix D twin, and the exactness table
# ---------------------------------------------------------------------------

FRAGMENT_HEADER = (
    "% Auto-generated by code/randomized_implementations.py.\n"
    "% Include this file with \\input{...}.\n"
    "% Requires: \\usepackage{booktabs}, \\usepackage{float}, and the thesis\n"
    "% macros \\TwoT, \\TwoO, \\TwoI, \\Tgroup, \\Ogroup, \\Igroup, \\Id,\n"
    "% \\Tr, \\SO, \\R, \\phig.\n"
    "% Regenerate with `cd code && uv run randomized_implementations.py`.\n\n"
)

# canonical display forms for the det witness, asserted against the computed
# values before anything is written (truth stays computed, display stays tidy).
#
# The signs here are the ATLAS's, and that is the whole point.  A determinant
# flips with the triple's handedness, so it belongs to the numbering, and this
# repo has two: symbolic_solids() numbers the tetrahedron, cube and icosahedron
# differently from the published atlas (povm_properties.py, tab:povm-atlas, and
# the data/povm_*.npz it exports).  Same solids, same pose, same vertex sets.
# Only the published one is printable, because the caption sends the reader
# there to look the indices up -- so the row must be the row they get.  Taking
# tab:povm-atlas's vertices 1, 2, 3 gives -4sqrt3/9 for the tetrahedron where
# symbolic_solids() gives +, and the icosahedron flips the other way; the cube,
# dodecahedron and octahedron happen to agree.  det_witness() runs on
# atlas_vertices() for exactly this reason, and the assert below pins the
# signed value, so a reordering trips a check instead of quietly reprinting.
DET_DISPLAY = {
    "tetrahedron": (-4 * sqrt(3) / 9, r"$-4\sqrt{3}/9$"),
    "octahedron": (sp.Integer(1), r"$+1$"),
    "cube": (-4 * sqrt(3) / 9, r"$-4\sqrt{3}/9$"),
    "icosahedron": (sqrt(10 - 2 * sqrt(5)) / 5,
                    r"$+\tfrac{1}{5}\sqrt{10-2\sqrt{5}}$"),
    "dodecahedron": (-4 * sqrt(3) / 9, r"$-4\sqrt{3}/9$"),
}

DEMAND_DISPLAY = {
    "tetrahedron": r"$\sqrt{3}$", "octahedron": "--- (none)",
    "cube": r"$\sqrt{3}$", "icosahedron": r"$\sqrt{5+2\sqrt{5}}$",
    "dodecahedron": r"$\sqrt{3}$",
}


# The thesis quotes these two rows' words in prose -- the octahedron's at
# four sites (one of them, F.3.3.2's closure sentence, in plain letters:
# see the witness display below), the cube's once (as a set, in another
# order) -- and a re-export must not move the table out from under them.
# Cheapest words are not unique: a re-export can legitimately reprint one
# cube axis (Z and Z† are the same rotation), three icosahedron axes and
# four dodecahedron axes -- never a cost or an effect -- while the
# octahedron's column is the one no tie-break can move. It is pinned
# anyway: that is measured, not enforced.
QUOTED_IN_PROSE = {
    "octahedron": r"$\Id$, $\mathbf{F}$, $\mathbf{F}^\dagger$",
    "cube": r"$\Id$, $\mathbf{F}$, $\mathbf{Z}$, $\mathbf{F}^\dagger$",
}


def latex_word(seq):
    """Atlas gate sequence -> LaTeX math, in the thesis's notation: the
    symmetrized gates bold, as in Appendix A (main.py's tex_seq), and Φ
    plain ('X F†' -> '$\\mathbf{X} \\mathbf{F}^\\dagger$', '' -> '$\\Id$')."""
    if seq in ("", "I"):
        return r"$\Id$"
    seq = re.sub(r"[XZFHS]", lambda m: r"\mathbf{" + m.group(0) + "}", seq)
    return "$" + seq.replace("Φ", r"\Phi").replace("†", r"^\dagger") + "$"


def coin_column(solid):
    """Sorted coin words and their (max depth, max magic), or None if no coin."""
    if not is_decomposable(load_vertices(solid)):
        return None
    g = COVARIANCE[solid]
    reps = coset_representatives(load_vertices(solid), load_rotations(g),
                                 best_circuits(load_atlas(g)))
    reps = sorted(reps, key=lambda r: (r[0], r[1], len(r[2]), r[2]))
    words = ", ".join(latex_word(seq) for _, _, seq in reps)
    if solid in QUOTED_IN_PROSE:
        assert words == QUOTED_IN_PROSE[solid], \
            (f"{solid} coin drifted from the words the thesis prints: "
             f"{words} != {QUOTED_IN_PROSE[solid]} -- the table and the prose "
             f"must be corrected together, not just regenerated")
    return words, max(r[1] for r in reps), max(r[0] for r in reps)


GROUP_TEX = {"T": r"\Tgroup", "O": r"\Ogroup", "I": r"\Igroup",
             # Klein four-group dressed as V_4: bare V is the thesis's vertex
             # count, and both senses print in tab:implementation-ledger.
             "V": "V_4", "C_3": "C_3", "C_4": "C_4", "C_5": "C_5",
             "D_3": "D_3", "D_4": "D_4", "D_5": "D_5", "1": r"\{\Id\}"}
DRAW_TEX = {12: r"\TwoT", 24: r"\TwoO", 60: r"\TwoI"}


def bar_cell(names, order):
    """'$C_4, V_4$ (4)' -- the subgroups at a bar, with the bar's order."""
    return "$" + ", ".join(GROUP_TEX[n] for n in names) + f"$ ({order})"


def spec_sheet():
    """Every cell of the master ledger, per solid, from the check primitives.

    One source of truth: the geometry off the canonical vertices, the
    register off V, the coin off coset_representatives, the two bars off
    two_bars/twirl_bar, the costs off the atlas's min-magic synthesis.
    """
    out = {}
    for solid in SOLIDS:
        s = load_vertices(solid)
        V = len(s)
        qb = math.ceil(math.log2(V))              # Naimark register dim >= V
        row = {"V": V, "design": design_strength(s), "qubits": qb,
               "dim": 2 ** qb, "dead": 2 ** qb - V,
               "demand": DEMAND_DISPLAY[solid], "twirl_bar": twirl_bar(solid)[0]}
        # The design column goes straight into the ledger the thesis prints,
        # and design_strength's docstring claims it agrees with
        # povm_properties' (2, 3, 3, 5, 5), so the claim is asserted here and
        # not merely made. The two derivations share no mechanism -- exact
        # moments over a number field there against float moment averaging
        # here -- so this is an independent verifier and not a control;
        # EXPECTED_DESIGN is the ladder's single source.
        assert row["design"] == EXPECTED_DESIGN[solid], (solid, row["design"])
        if not is_decomposable(s):
            assert solid == "tetrahedron"
            out[solid] = {**row, "axes": None, "coin": None, "realize": None,
                          "binds": None, "draw": 12, "draw_cost": None}
            continue
        b = two_bars(solid)
        assert b["bar_twirl"] == row["twirl_bar"]  # R1 and R2 agree on the bar
        R = b["rotations"]
        circuits = best_circuits(load_atlas(b["group"]))
        reps = coset_representatives(s, R, circuits)
        # the cheapest draw clearing both bars (several may tie at the draw)
        bill = min((max(circuits[rot_key(R[i])][0] for i in S),
                    max(circuits[rot_key(R[i])][1] for i in S))
                   for S in b["draw_groups"])
        out[solid] = {**row, "axes": V // 2,
                      "coin": (len(reps), max(r[1] for r in reps),
                               max(r[0] for r in reps)),
                      "realize": bar_cell(b["min_realize"], b["bar_realize"]),
                      "binds": b["binds"], "draw": b["draw"],
                      "draw_cost": (bill[1], bill[0])}
    return out


def write_fragments():
    """Emit the six LaTeX fragments into data/, post-verification.

    tab:implementation-ledger (the Section 5.2.3 master spec sheet, solids as
    columns), tab:decker-vs-coin, tab:povm-exactness and tab:decker-labels
    (Appendix D), and for Appendix F.3.3 the tab:two-bars-sweep detail table
    plus the C_3 witness display -- the last a bare equation, not a table.
    One source of truth: every number, gate sequence and matrix entry is
    recomputed from the same loaders and primitives the checks used;
    captions live here, not in the .tex. Only reached when the whole suite
    has passed (see __main__).
    """
    atlas_I = load_atlas("I")
    mean_phi = float(atlas_I["dij_magic_costs"].mean())
    spec = spec_sheet()

    # --- the Section 5.2.3 ledger: one transposed master spec sheet ----------
    # Solids are COLUMNS. Read across, the two-bars block is the finding
    # itself: a realize row climbing 3, 4, 12, 60 against a dead-flat twirl
    # row of 12s, crossing at the icosahedron.
    def across(f, dash="---"):
        return " & ".join(dash if (x := f(spec[s])) is None else str(x)
                          for s in SOLIDS)

    def block(title):
        return (f"\\addlinespace[2pt]\n\\multicolumn{{6}}{{l}}"
                f"{{\\textit{{{title}}}}} \\\\\n")

    def row(label, f, dash="---"):
        return f"\\quad {label} & {across(f, dash)} \\\\\n"

    body = (
        block("The solid")
        + row("Vertices $V$", lambda r: r["V"])
        + row("Vertex axes", lambda r: r["axes"])
        + row("Spherical design $t$", lambda r: r["design"])
        + row("Field demand", lambda r: r["demand"])
        + block("Native route (Decker's dilation)")
        + row("Naimark register", lambda r: f"{r['qubits']}\\,qb ({r['dim']})")
        + row("Dead outcomes", lambda r: r["dead"])
        + block("Projective route (the coin)")
        + row("Coin words, one per axis", lambda r: r["coin"] and r["coin"][0])
        + row("Coin cost (depth\\,/\\,$\\Phi$)",
              lambda r: r["coin"] and f"${r['coin'][1]} / {r['coin'][2]}$")
        # Block titles name their contents, not the metaphor: a reader who
        # opens the thesis at this table has not met "the two bars".
        + block("Realization vs.\\ twirling")
        + row("Smallest group that realizes", lambda r: r["realize"])
        + row("Smallest group that twirls",
              lambda r: f"$\\Tgroup$ ({r['twirl_bar']})")
        + row("Which one binds", lambda r: r["binds"])
        + block("The draw (clears both)")
        + row("Group", lambda r: f"${DRAW_TEX[r['draw']]}"
              + ("^{\\ast}$" if r["binds"] is None else "$"))
        + row("Draw cost (depth\\,/\\,$\\Phi$)",
              lambda r: r["draw_cost"] and f"${r['draw_cost'][0]} / {r['draw_cost'][1]}$")
    )
    ledger = (
        FRAGMENT_HEADER
        # [h], not the [H] the other two table fragments use: under [H] the
        # ledger cannot fit after the paragraph that sets it up, so it
        # abandons two thirds of that page and starts overleaf; under [h] it
        # floats to the top of the next page and the prose closes underneath,
        # which is a page cheaper. It lives here because a hand patch in
        # data/ would be silently reverted by any regeneration.
        + "\\begin{table}[h]\\centering\n\\small\n"
        # arraystretch 1.05, not 1.15: the float box must clear the 350 pt
        # float-page cliff (\textheight 700.51 pt times \floatpagefraction
        # 0.5) to share a page with Section 5.2.3's prose; the 22-row body
        # alone runs ~300 pt at 1.15, leaving the caption three lines, and
        # the box with its caption goes well past the cliff there -- a page
        # of its own.
        + "\\setlength{\\tabcolsep}{4.5pt}\n\\renewcommand{\\arraystretch}{1.05}\n"
        + "\\begin{tabular}{l c c c c c}\n\\toprule\n"
        + " & " + " & ".join(s.capitalize() for s in SOLIDS) + " \\\\\n"
        + "\\midrule\n" + body + "\\bottomrule\n\\end{tabular}\n"
        # The caption leads claims-first: only the octahedron exact, the
        # twirl bar flat while realization climbs, 2T draws every solid but
        # the dodecahedron. The glosses (Naimark register, dead outcomes,
        # the cost-pair exclusions) belong here rather than in
        # tab:decker-vs-coin's caption -- a caption glosses its own table,
        # not another. Field demand stays defined in Section 5.1
        # (sec:magicfindings), realizes/twirls in Table F.2's caption and
        # F.3.3's lead; the SO(3) classification lives in the prose and in
        # F.3.3.  "Whose draw needs": the 2I and its 0.8 price the draw,
        # never the coin --- the coin realizes only, and the twin caption's
        # "no group below order 12" says the same.
        + "\\caption{The implementation ledger. Only the octahedron is exact "
          "(Section~\\ref{sec:magicfindings}); the twirl bar sits at "
          "$\\Tgroup$ for every solid while realization climbs $3$, $4$, "
          "$12$, $60$, so a $\\TwoT$ draw clears both for all but the "
          f"dodecahedron, whose draw needs $\\TwoI$ (${mean_phi:.1f}\\,\\Phi$ "
          "per shot on average). \\textit{Naimark register} counts qubits, "
          "data included, with the register dimension; \\textit{dead "
          "outcomes} are computational results that are zero effects by "
          "construction; cost pairs are maxima over the min-$\\Phi$ atlas "
          "words, the alignment and the native corrections excluded. "
          "$^{\\ast}$No coin; $\\TwoT$ is its twirled-native draw.}\n"
        + "\\label{tab:implementation-ledger}\n\\end{table}\n"
    )

    # --- the Appendix D twin, now carrying only what the ledger cannot: the
    # --- coin's WORDS. Register, dead outcomes and axis counts moved into
    # --- the master table, so main text = the ledger of facts, appendix =
    # --- the coin words.
    rows = []
    for solid in SOLIDS:
        coin = coin_column(solid)
        if coin is None:
            words = "--- (indecomposable; the dilation is forced)"
            depth = magic = "---"
        else:
            words, d_max, m_max = coin
            depth = rf"$\le {d_max}$"
            # Bare $0$ rather than $\le 0$: no word carries a $\Phi$ at all.
            magic = f"${m_max}$" if m_max == 0 else rf"$\le {m_max}$"
        rows.append(f"  {solid.capitalize()} ({len(load_vertices(solid))})"
                    f" & {words} & {depth} & {magic} \\\\")
    twin = (
        FRAGMENT_HEADER
        + "\\begin{table}[H]\\centering\n\\small\n"
        + "\\setlength{\\tabcolsep}{6pt}\n\\renewcommand{\\arraystretch}{1.2}\n"
        # Cost split into Depth/$\Phi$ subcolumns: the words "depth" and
        # "$\Phi$" belong in the header, not repeated down every row. The
        # \le stays in the cells -- these are maxima over the coin's words,
        # and the sign says so without a caption gloss.
        + "\\begin{tabular}{l l c c}\n\\toprule\n"
        + " & & \\multicolumn{2}{c}{Coin cost} \\\\\n"
        + "\\cmidrule(lr){3-4}\n"
        + "POVM ($V$) & Coin words (min-$\\Phi$) & Depth & $\\Phi$ \\\\\n"
        + "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n"
        # The glosses for tab:implementation-ledger live in that table's
        # own caption, not this one; keeping them out also leaves Appendix
        # D's last page its slack.
        + "\\caption{The realizing coin over axes: one atlas circuit per "
          "Platonic solid POVM vertex axis (min-$\\Phi$ synthesis, one word "
          "per antipodal pair). A uniform draw reproduces the POVM's effects "
          "exactly. These words replace Decker's ancilla register; what "
          "they do not replace is the fixed \\textit{alignment} rotation "
          "every projective shot applies after the drawn word, on which the "
          "field demand of Table~\\ref{tab:implementation-ledger} is "
          "paid---the identity for the octahedron, inexact for every other "
          "solid (Theorem~\\ref{thm:main}). The cost columns price this "
          "realizing coin alone; Table~\\ref{tab:implementation-ledger}'s "
          "\\textit{draw} costs more because a single draw must also twirl, "
          "which no group below order $12$ can do. (For the dodecahedron "
          "the gap is forced by transitivity rather than by the twirl; "
          "Section~\\ref{sec:povmsinuse}.)}\n"
        + "\\label{tab:decker-vs-coin}\n\\end{table}\n"
    )

    # --- the Appendix F.3.3.1 sweep-detail table --------------------------
    rows = []
    for solid in ("octahedron", "cube", "icosahedron", "dodecahedron"):
        b = two_bars(solid)
        R = b["rotations"]

        def orders(subs, R=R):
            return ", ".join(f"${o}^{{\\times {c}}}$" if c > 1 else f"${o}$"
                             for o, (c, _) in by_order(R, subs).items())
        rows.append(
            f"  {solid.capitalize()} & ${len(b['subgroups'])}$ "
            f"(${GROUP_TEX[b['group']]}$) & {orders(b['realize'])}"
            f" & {orders(b['twirl'])}"
            f" & {bar_cell(b['min_realize'], b['bar_realize'])}"
            f" & {bar_cell(b['min_twirl'], b['bar_twirl'])}"
            f" & {b['binds']} \\\\")
    sweep = (
        FRAGMENT_HEADER
        + "\\begin{table}[H]\\centering\n\\small\n"
        + "\\setlength{\\tabcolsep}{5pt}\n\\renewcommand{\\arraystretch}{1.2}\n"
        + "\\begin{tabular}{l c l l l l c}\n\\toprule\n"
        # No "bar" in a thesis-facing string: the metaphor is coined in the
        # F.3.3 prose, and this table must read cold. "Smallest realizing"
        # matches Table 5.2's row labels and measures 448.4pt of the 453pt
        # textwidth -- "Smallest that realizes" overfulls at 477.4pt.
        + "POVM & Lattice & Realizing & Twirling & Smallest realizing"
          " & Smallest twirling & Binds \\\\\n"
        + "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n"
        # The caption stays at ~110 words: it glosses Lattice, Realizing and
        # Twirling and states both qualifying tests, but not the bar columns
        # -- which bar binds which solid, and why, is the prose's job
        # (Section 5.2.3, and F.3.3's first paragraph for the dodecahedron's
        # ten axes lying out of reach of every proper subgroup of I). The
        # finding that the twirling column IS the set of irreducible
        # subgroups -- the protocol test recovering Schur -- is pinned in
        # F.3.3.1's prose lead as well as here.
        + "\\caption{Realization versus twirling, swept exhaustively over "
          "every subgroup of the solid's rotation group. \\textit{Lattice}: "
          "the number of subgroups; $30$ and $59$ are the known subgroup "
          "counts of $S_4$ and $A_5$. \\textit{Realizing} and "
          "\\textit{Twirling} list the qualifying subgroups by order, with "
          "multiplicity: a draw realizes when its orbit of the alignment "
          "vertex, read out both ways, is the whole vertex set, uniformly, "
          "and twirls when its estimator channel comes out exactly "
          "depolarizing. The twirling column is exactly the set of "
          "\\textit{irreducible} subgroups. Ranging over "
          "the covariance group suffices: a draw whose orbit is the "
          "whole vertex set permutes that set, hence lies inside the solid's "
          "rotation group already.}\n"
        + "\\label{tab:two-bars-sweep}\n\\end{table}\n"
    )

    # --- the Appendix F.3.3.2 witness display -----------------------------
    # Not a table: the C_3 counterexample, stated symbolically so that no
    # probe matrix reaches the thesis. Deliberately the SAME two averages
    # Appendix F.3.1 already displays -- the twirl of readout-times-noise and
    # the mean sampled vertex -- so the reader sees exactly which of its two
    # identities a reducible draw breaks. Both sides are computed here, not
    # typed; rank_one_twirl returns 3 x the average (the canonical dual's
    # factor), so the displayed averages carry an explicit 1/3.  The header
    # prints the coin in PLAIN letters, unlike the ledger tables: C_3 is the
    # coin's rotations (exact_coin_is_group tests SO(3)), and the SU(2) triple
    # is not a group -- F_SU(2)^2 = -F_SU(2)^dagger -- so bold would claim a
    # group structure that does not exist (thesis F.3.3.2).
    tex = {"mat_str": "pmatrix", "mat_delim": ""}
    a, b_, c = sp.symbols("T_zx T_zy T_zz", real=True)
    R_F = bloch_matrix(atlas_gates()["F"])
    zhat, w = Matrix([0, 0, 1]), Matrix([a, b_, c])
    M3, o3 = rank_one_twirl([sp.eye(3), R_F, R_F * R_F], zhat, w)
    MT, oT = rank_one_twirl(exact_rotations("T"), zhat, w)
    M3, o3, MT, oT = (sp.simplify(x) for x in (M3, o3, MT, oT))
    assert MT == c * sp.eye(3) and oT == sp.zeros(3, 1), (MT, oT)
    assert o3 == Matrix([1, 1, 1]), o3
    lhs1 = (r"\dfrac{1}{|G|}\sum_{g \in G} R_g^\top\, \hat z \hat z^\top T\, R_g")
    lhs2 = r"\dfrac{1}{|G|}\sum_{g \in G} R_g^\top \hat z"
    witness = (
        FRAGMENT_HEADER
        + "\\begin{equation*}\n"
        + "  \\begin{array}{l@{\\qquad}c@{\\qquad}c}\n"
        + "     & \\text{over the coin } C_3 = \\{\\Id, F, F^\\dagger\\}"
          " & \\text{over } \\Tgroup \\\\[6pt]\n"
        + f"    {lhs1} & \\dfrac{{1}}{{3}}\\,{sp.latex(M3, **tex)}"
          f" & \\dfrac{{{sp.latex(c)}}}{{3}}\\,\\Id_3 \\\\[16pt]\n"
        + f"    {lhs2} & \\tfrac{{1}}{{3}}\\,{sp.latex(o3.T, **tex)}^{{\\top}}"
          f" & {sp.latex(oT[0])}\n"
        + "  \\end{array}\n"
        + "\\end{equation*}\n"
    )

    # --- the Appendix D exactness table ------------------------------------
    # atlas_vertices(), not symbolic_solids(): the (a,b,c) column is printed and
    # the caption sends the reader to tab:povm-atlas to look it up, so indices,
    # sign and magnitude all have to be the reader's.  See DET_DISPLAY.
    solids_sym = {s: atlas_vertices(s) for s in SOLIDS}
    x = sp.Symbol("x")
    rows = []
    for solid in SOLIDS:
        trip, d = det_witness(solids_sym[solid])
        val, shown = DET_DISPLAY[solid]
        assert sp.simplify(d - val) == 0, (solid, d)
        mp = sp.minimal_polynomial(d, x)
        idx = ",".join(str(i) for i in trip)
        rows.append(f"  {solid.capitalize()} & $({idx})$ & {shown}"
                    f" & ${sp.latex(mp)}$ & {DEMAND_DISPLAY[solid]} \\\\")
    exactness = (
        FRAGMENT_HEADER
        # [h], not [H] -- the same story as the ledger above: it lives here
        # because a hand patch in data/ would be silently reverted by any
        # regeneration.
        + "\\begin{table}[h]\\centering\n"
        + "\\renewcommand{\\arraystretch}{1.2}\n"
        + "\\begin{tabular}{l c c c c}\n\\toprule\n"
        + "Solid & $(a,b,c)$ & $\\det[v_a\\,v_b\\,v_c]$ & Minimal polynomial "
          "& Demands \\\\\n"
        + "\\midrule\n" + "\n".join(rows) + "\n"
        # midrule sandwich: the icosahedron row's two surds look unrelated
        # and are one extension.  Measured at 414.34pt against \textwidth
        # 452.97pt -- the identities fit, naming their provenance too does
        # not (498.62pt), so that half of the finding lives in the caption.
        # This row, not any data row, is what sets the tabular's width, which
        # is why the (a,b,c) column costs nothing.
        + "\\midrule\n"
        + "\\multicolumn{5}{c}{One extension, three names: "
          "$\\sqrt{5+2\\sqrt{5}} = \\phig\\sqrt{2+\\phig}$ and "
          "$\\sqrt{10-2\\sqrt{5}} = (2/\\phig)\\sqrt{2+\\phig}$.} \\\\\n"
        + "\\bottomrule\n\\end{tabular}\n"
        + "\\caption{The exactness obstruction. Here $v_a, v_b, v_c$ is the "
          "solid's first vertex triple spanning $\\R^3$, numbered and posed "
          "as in Appendix~\\ref{sec:povm-atlas:vertices}. The triple is a "
          "choice, but every spanning triple's determinant is a "
          "$K_\\R$-multiple of the one shown, so any one decides "
          "(Lemma~\\ref{lem:witness}), and the determinant is unchanged by "
          "rotation, so no pose escapes the test. The minimal polynomial "
          "pins each determinant exactly; degree four alone bars nothing, "
          "$K_\\R$ having degree four, and Lemma~\\ref{lem:membership} "
          "gives the verdict, barring all three surds of the footer row by "
          "naming $2+\\phig = \\tfrac{1}{2}(5+\\sqrt{5})$ and the determinant's square. Only the "
          "octahedron survives this test. Computed symbolically by "
          "\\texttt{code/randomized\\_implementations.py}.}\n"
        + "\\label{tab:povm-exactness}\n\\end{table}\n"
    )

    # --- the Appendix D outcome-order table (tab:decker-labels) ------------
    # Permutation and kappa recomputed from the same primitives
    # check_decker_outcome_order asserted with: the permutation reads the
    # rebuilt circuit against the atlas through Table D.3's reorientation,
    # kappa through no correction at all -- the circuit as published,
    # outcomes read against the atlas list index for index. The cell is
    # two-line notation keyed by register value: three solids' live
    # outcomes are non-contiguous and the atlas numbers vertices from 1,
    # so neither row of the map may be left an implicit range(). The
    # column prints even though each card carries its own
    # register-to-vertex key: reading a card's rectangle key means decoding
    # the register in base 2, while the column reads at sight. The % key
    # comment lines are the machine-readable twin --
    # _build_povm_cards.py's assertion 15 and _build_recipe_figure.py read
    # them, and the card build's parse asserts print and twin equal.
    rows, keys = [], []
    for solid in SOLIDS:
        d, live, W = decker_vertices(solid)
        n = load_vertices(solid)
        V = len(n)
        assert live == sorted(live) and len(live) == V, solid
        dead = sorted(set(range(len(W))) - set(live))
        assert all(np.linalg.norm(W[k]) < 1e-12 for k in dead), solid
        R = np.array(REORIENT[solid][1], dtype=float)
        perm = []
        for vx in d:
            dist = np.linalg.norm(n - R @ vx, axis=1)
            near = np.sort(dist)[:2]
            assert near[0] < 1e-9 and near[1] > 0.1, (solid, near)
            perm.append(int(np.argmin(dist)))
        assert sorted(perm) == list(range(V)), solid
        kappa = float(np.mean([n[k] @ d[k] for k in range(V)]))
        # relabelling without the gate leaves the overlap at tr(R)/3
        # exactly (D.2's angle law), and the tetrahedron's printed row
        # (relabelling trivial) prices exactly that gap. The caption says
        # nothing of it: that row is the one solid where the half-measure is
        # benign, and it hides the octahedron's -0.179 (a 31x premium, worse
        # than skipping both corrections).
        kappa_perm = float(np.mean([n[perm[i]] @ d[i] for i in range(V)]))
        assert abs(kappa_perm - np.trace(R) / 3) < 1e-12, solid
        if solid == "tetrahedron":
            assert perm == list(range(V)) and kappa == kappa_perm
        top = " ".join(str(j) for j in live)
        bot = " ".join(str(p + 1) for p in perm)
        keys.append(f"% key {solid}: {top} -> {bot}")
        pi_cell = ("$\\bigl(\\begin{smallmatrix} "
                   + " & ".join(str(j) for j in live) + " \\\\ "
                   + " & ".join(str(p + 1) for p in perm)
                   + " \\end{smallmatrix}\\bigr)$")
        if solid == "cube":
            assert abs(kappa + 1 / 3) < 1e-12, kappa
            kap_cell = "$-1/3$ exactly"
        else:
            kap_cell = f"${kappa:+.6f}$"
        rows.append(f"  {solid.capitalize()} & {pi_cell} & {kap_cell}"
                    f" & ${1 / kappa ** 2:.2f}$ \\\\")
    labels = (
        FRAGMENT_HEADER
        + "% The register-to-vertex key of each solid, live computational\n"
          "% outcome (from 0) -> our vertex (from 1); printed in the table\n"
          "% below and on the cards, read here by code/_build_povm_cards.py\n"
          "% and code/_build_recipe_figure.py.\n"
        + "\n".join(keys) + "\n"
        + "\\begin{table}[h]\\centering\n\\small\n"
        + "\\setlength{\\tabcolsep}{5pt}\n"
        + "\\renewcommand{\\arraystretch}{1.2}\n"
        + "\\begin{tabular}{l l c c}\n\\toprule\n"
        + "Solid & Outcome (from $0$) $\\mapsto$ our vertex (from $1$) "
          "& $\\kappa$ & $1/\\kappa^{2}$ \\\\\n"
        + "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n"
        + "\\caption{Decker's outcome order, and the price of ignoring it. The "
          "permutation column records, in two-line notation, the relabelling "
          "owed once the reorientation of Table~\\ref{tab:decker-pose} is "
          "applied: the top row holds the live computational outcomes of "
          "Figures~\\ref{fig:dec_tet_circuit}--\\ref{fig:dec_dodec_circuit}, "
          "top wire first, and beneath each is the vertex it then fires as, "
          "numbered from $1$ as in Appendix~\\ref{sec:povm-atlas:vertices}; "
          "outcomes absent from a top row are dead and never fire. This "
          "permutes Decker's own printed vertex numbering, which the adapted "
          "circuits reproduce. Run $U_R$ and relabel, or skip $U_R$ and read "
          "Decker's own numbered list: either way $\\kappa = 1$. The column "
          "prices a mismatch, his circuit as published with our list, "
          "index for index. No misspecified belief can tilt a twirled "
          "estimator: the estimator channel is $\\kappa\\,\\Id$ with zero "
          "offset, $\\kappa$ the overlap of the believed vertex list with the "
          "measured one, ideal $1$, and the whole bill is a $1/\\kappa^{2}$ "
          "premium in shots. The $\\kappa$ column runs on the estimator's "
          "scale, not the calibration's $1/3$. The failure modes nest from "
          "harmless to hostile: the tetrahedron pays the premium and nothing "
          "more; the cube's exact $-1/3$ also flips the calibration's sign, "
          "inviting the discard of a salvageable run; at the dodecahedron's "
          "$\\kappa \\approx 0$ the channel is indistinguishable from heavy "
          "depolarizing noise, a labelling bug charged to the hardware. "
          "Computed in \\texttt{code/randomized\\_implementations.py}.}\n"
        + "\\label{tab:decker-labels}\n\\end{table}\n"
    )

    for name, content in (("randomized_ledger.tex", ledger),
                          ("randomized_ledger_appendix.tex", twin),
                          ("randomized_sweep.tex", sweep),
                          ("randomized_witness.tex", witness),
                          ("randomized_exactness.tex", exactness),
                          ("randomized_labels.tex", labels)):
        with open(DATA + name, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"[ok] wrote data/{name}")
